// DO NOT EDIT!
// csharp generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace services
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetUserNotificationsRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GetUserNotificationsRequest GetRootAsGetUserNotificationsRequest(ByteBuffer _bb) { return GetRootAsGetUserNotificationsRequest(_bb, new GetUserNotificationsRequest()); }
  public static GetUserNotificationsRequest GetRootAsGetUserNotificationsRequest(ByteBuffer _bb, GetUserNotificationsRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetUserNotificationsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string UserId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUserIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUserIdArray() { return __p.__vector_as_array<byte>(4); }
  public int Limit { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Offset { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public common.Status StatusFilter { get { int o = __p.__offset(10); return o != 0 ? (common.Status)__p.bb.GetInt(o + __p.bb_pos) : common.Status.STATUS_UNKNOWN; } }

  public static Offset<services.GetUserNotificationsRequest> CreateGetUserNotificationsRequest(FlatBufferBuilder builder,
      StringOffset user_idOffset = default(StringOffset),
      int limit = 0,
      int offset = 0,
      common.Status status_filter = common.Status.STATUS_UNKNOWN) {
    builder.StartTable(4);
    GetUserNotificationsRequest.AddStatusFilter(builder, status_filter);
    GetUserNotificationsRequest.AddOffset(builder, offset);
    GetUserNotificationsRequest.AddLimit(builder, limit);
    GetUserNotificationsRequest.AddUserId(builder, user_idOffset);
    return GetUserNotificationsRequest.EndGetUserNotificationsRequest(builder);
  }

  public static void StartGetUserNotificationsRequest(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddUserId(FlatBufferBuilder builder, StringOffset userIdOffset) { builder.AddOffset(0, userIdOffset.Value, 0); }
  public static void AddLimit(FlatBufferBuilder builder, int limit) { builder.AddInt(1, limit, 0); }
  public static void AddOffset(FlatBufferBuilder builder, int offset) { builder.AddInt(2, offset, 0); }
  public static void AddStatusFilter(FlatBufferBuilder builder, common.Status statusFilter) { builder.AddInt(3, (int)statusFilter, 0); }
  public static Offset<services.GetUserNotificationsRequest> EndGetUserNotificationsRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<services.GetUserNotificationsRequest>(o);
  }
}


static public class GetUserNotificationsRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*UserId*/, false)
      && verifier.VerifyField(tablePos, 6 /*Limit*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Offset*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*StatusFilter*/, 4 /*common.Status*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
