// DO NOT EDIT!
// csharp generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace services
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MarkNotificationAsReadRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MarkNotificationAsReadRequest GetRootAsMarkNotificationAsReadRequest(ByteBuffer _bb) { return GetRootAsMarkNotificationAsReadRequest(_bb, new MarkNotificationAsReadRequest()); }
  public static MarkNotificationAsReadRequest GetRootAsMarkNotificationAsReadRequest(ByteBuffer _bb, MarkNotificationAsReadRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MarkNotificationAsReadRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string NotificationId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNotificationIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNotificationIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNotificationIdArray() { return __p.__vector_as_array<byte>(4); }
  public string UserId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUserIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUserIdArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<services.MarkNotificationAsReadRequest> CreateMarkNotificationAsReadRequest(FlatBufferBuilder builder,
      StringOffset notification_idOffset = default(StringOffset),
      StringOffset user_idOffset = default(StringOffset)) {
    builder.StartTable(2);
    MarkNotificationAsReadRequest.AddUserId(builder, user_idOffset);
    MarkNotificationAsReadRequest.AddNotificationId(builder, notification_idOffset);
    return MarkNotificationAsReadRequest.EndMarkNotificationAsReadRequest(builder);
  }

  public static void StartMarkNotificationAsReadRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddNotificationId(FlatBufferBuilder builder, StringOffset notificationIdOffset) { builder.AddOffset(0, notificationIdOffset.Value, 0); }
  public static void AddUserId(FlatBufferBuilder builder, StringOffset userIdOffset) { builder.AddOffset(1, userIdOffset.Value, 0); }
  public static Offset<services.MarkNotificationAsReadRequest> EndMarkNotificationAsReadRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<services.MarkNotificationAsReadRequest>(o);
  }
}


static public class MarkNotificationAsReadRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*NotificationId*/, false)
      && verifier.VerifyString(tablePos, 6 /*UserId*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
