// DO NOT EDIT!
// csharp generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace services
{

public enum NotificationType : int
{
  NOTIFICATION_TYPE_UNKNOWN = 0,
  NOTIFICATION_TYPE_EMAIL = 1,
  NOTIFICATION_TYPE_SMS = 2,
  NOTIFICATION_TYPE_PUSH = 3,
  NOTIFICATION_TYPE_IN_APP = 4,
};


}
