// DO NOT EDIT!
// csharp generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace services
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UpdateUserStatusRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static UpdateUserStatusRequest GetRootAsUpdateUserStatusRequest(ByteBuffer _bb) { return GetRootAsUpdateUserStatusRequest(_bb, new UpdateUserStatusRequest()); }
  public static UpdateUserStatusRequest GetRootAsUpdateUserStatusRequest(ByteBuffer _bb, UpdateUserStatusRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UpdateUserStatusRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string UserId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUserIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUserIdArray() { return __p.__vector_as_array<byte>(4); }
  public common.Status NewStatus { get { int o = __p.__offset(6); return o != 0 ? (common.Status)__p.bb.GetInt(o + __p.bb_pos) : common.Status.STATUS_UNKNOWN; } }

  public static Offset<services.UpdateUserStatusRequest> CreateUpdateUserStatusRequest(FlatBufferBuilder builder,
      StringOffset user_idOffset = default(StringOffset),
      common.Status new_status = common.Status.STATUS_UNKNOWN) {
    builder.StartTable(2);
    UpdateUserStatusRequest.AddNewStatus(builder, new_status);
    UpdateUserStatusRequest.AddUserId(builder, user_idOffset);
    return UpdateUserStatusRequest.EndUpdateUserStatusRequest(builder);
  }

  public static void StartUpdateUserStatusRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUserId(FlatBufferBuilder builder, StringOffset userIdOffset) { builder.AddOffset(0, userIdOffset.Value, 0); }
  public static void AddNewStatus(FlatBufferBuilder builder, common.Status newStatus) { builder.AddInt(1, (int)newStatus, 0); }
  public static Offset<services.UpdateUserStatusRequest> EndUpdateUserStatusRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<services.UpdateUserStatusRequest>(o);
  }
}


static public class UpdateUserStatusRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*UserId*/, false)
      && verifier.VerifyField(tablePos, 6 /*NewStatus*/, 4 /*common.Status*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
