// DO NOT EDIT!
// csharp generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace services
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct User : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static User GetRootAsUser(ByteBuffer _bb) { return GetRootAsUser(_bb, new User()); }
  public static User GetRootAsUser(ByteBuffer _bb, User obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string UserId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUserIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUserIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Email { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmailBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetEmailBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetEmailArray() { return __p.__vector_as_array<byte>(6); }
  public string FirstName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFirstNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetFirstNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetFirstNameArray() { return __p.__vector_as_array<byte>(8); }
  public string LastName { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLastNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetLastNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetLastNameArray() { return __p.__vector_as_array<byte>(10); }
  public common.Address? Address { get { int o = __p.__offset(12); return o != 0 ? (common.Address?)(new common.Address()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public common.Status Status { get { int o = __p.__offset(14); return o != 0 ? (common.Status)__p.bb.GetInt(o + __p.bb_pos) : common.Status.STATUS_UNKNOWN; } }
  public common.Timestamp? CreatedAt { get { int o = __p.__offset(16); return o != 0 ? (common.Timestamp?)(new common.Timestamp()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public common.Timestamp? UpdatedAt { get { int o = __p.__offset(18); return o != 0 ? (common.Timestamp?)(new common.Timestamp()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string Roles(int j) { int o = __p.__offset(20); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int RolesLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<services.User> CreateUser(FlatBufferBuilder builder,
      StringOffset user_idOffset = default(StringOffset),
      StringOffset emailOffset = default(StringOffset),
      StringOffset first_nameOffset = default(StringOffset),
      StringOffset last_nameOffset = default(StringOffset),
      Offset<common.Address> addressOffset = default(Offset<common.Address>),
      common.Status status = common.Status.STATUS_UNKNOWN,
      Offset<common.Timestamp> created_atOffset = default(Offset<common.Timestamp>),
      Offset<common.Timestamp> updated_atOffset = default(Offset<common.Timestamp>),
      VectorOffset rolesOffset = default(VectorOffset)) {
    builder.StartTable(9);
    User.AddRoles(builder, rolesOffset);
    User.AddUpdatedAt(builder, updated_atOffset);
    User.AddCreatedAt(builder, created_atOffset);
    User.AddStatus(builder, status);
    User.AddAddress(builder, addressOffset);
    User.AddLastName(builder, last_nameOffset);
    User.AddFirstName(builder, first_nameOffset);
    User.AddEmail(builder, emailOffset);
    User.AddUserId(builder, user_idOffset);
    return User.EndUser(builder);
  }

  public static void StartUser(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddUserId(FlatBufferBuilder builder, StringOffset userIdOffset) { builder.AddOffset(0, userIdOffset.Value, 0); }
  public static void AddEmail(FlatBufferBuilder builder, StringOffset emailOffset) { builder.AddOffset(1, emailOffset.Value, 0); }
  public static void AddFirstName(FlatBufferBuilder builder, StringOffset firstNameOffset) { builder.AddOffset(2, firstNameOffset.Value, 0); }
  public static void AddLastName(FlatBufferBuilder builder, StringOffset lastNameOffset) { builder.AddOffset(3, lastNameOffset.Value, 0); }
  public static void AddAddress(FlatBufferBuilder builder, Offset<common.Address> addressOffset) { builder.AddOffset(4, addressOffset.Value, 0); }
  public static void AddStatus(FlatBufferBuilder builder, common.Status status) { builder.AddInt(5, (int)status, 0); }
  public static void AddCreatedAt(FlatBufferBuilder builder, Offset<common.Timestamp> createdAtOffset) { builder.AddOffset(6, createdAtOffset.Value, 0); }
  public static void AddUpdatedAt(FlatBufferBuilder builder, Offset<common.Timestamp> updatedAtOffset) { builder.AddOffset(7, updatedAtOffset.Value, 0); }
  public static void AddRoles(FlatBufferBuilder builder, VectorOffset rolesOffset) { builder.AddOffset(8, rolesOffset.Value, 0); }
  public static VectorOffset CreateRolesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRolesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRolesVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRolesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRolesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<services.User> EndUser(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<services.User>(o);
  }
}


static public class UserVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*UserId*/, false)
      && verifier.VerifyString(tablePos, 6 /*Email*/, false)
      && verifier.VerifyString(tablePos, 8 /*FirstName*/, false)
      && verifier.VerifyString(tablePos, 10 /*LastName*/, false)
      && verifier.VerifyTable(tablePos, 12 /*Address*/, common.AddressVerify.Verify, false)
      && verifier.VerifyField(tablePos, 14 /*Status*/, 4 /*common.Status*/, 4, false)
      && verifier.VerifyTable(tablePos, 16 /*CreatedAt*/, common.TimestampVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 18 /*UpdatedAt*/, common.TimestampVerify.Verify, false)
      && verifier.VerifyVectorOfStrings(tablePos, 20 /*Roles*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
