# DO NOT EDIT!
# python generated by Buffman 💪
# Versions:
# 		Buffman: 1.0.0
# 		Flatc: v25.2.10

# namespace: services

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CreateUserRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreateUserRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreateUserRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CreateUserRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CreateUserRequest
    def Email(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CreateUserRequest
    def FirstName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CreateUserRequest
    def LastName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CreateUserRequest
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from common.Address import Address
            obj = Address()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CreateUserRequest
    def Roles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # CreateUserRequest
    def RolesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CreateUserRequest
    def RolesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def CreateUserRequestStart(builder):
    builder.StartObject(5)

def Start(builder):
    CreateUserRequestStart(builder)

def CreateUserRequestAddEmail(builder, email):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(email), 0)

def AddEmail(builder, email):
    CreateUserRequestAddEmail(builder, email)

def CreateUserRequestAddFirstName(builder, firstName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(firstName), 0)

def AddFirstName(builder, firstName):
    CreateUserRequestAddFirstName(builder, firstName)

def CreateUserRequestAddLastName(builder, lastName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(lastName), 0)

def AddLastName(builder, lastName):
    CreateUserRequestAddLastName(builder, lastName)

def CreateUserRequestAddAddress(builder, address):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)

def AddAddress(builder, address):
    CreateUserRequestAddAddress(builder, address)

def CreateUserRequestAddRoles(builder, roles):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(roles), 0)

def AddRoles(builder, roles):
    CreateUserRequestAddRoles(builder, roles)

def CreateUserRequestStartRolesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRolesVector(builder, numElems):
    return CreateUserRequestStartRolesVector(builder, numElems)

def CreateUserRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return CreateUserRequestEnd(builder)
