# DO NOT EDIT!
# python generated by Buffman 💪
# Versions:
# 		Buffman: 1.0.0
# 		Flatc: v25.2.10

# namespace: services

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetUserNotificationsRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetUserNotificationsRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetUserNotificationsRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetUserNotificationsRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetUserNotificationsRequest
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GetUserNotificationsRequest
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GetUserNotificationsRequest
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GetUserNotificationsRequest
    def StatusFilter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def GetUserNotificationsRequestStart(builder):
    builder.StartObject(4)

def Start(builder):
    GetUserNotificationsRequestStart(builder)

def GetUserNotificationsRequestAddUserId(builder, userId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(userId), 0)

def AddUserId(builder, userId):
    GetUserNotificationsRequestAddUserId(builder, userId)

def GetUserNotificationsRequestAddLimit(builder, limit):
    builder.PrependInt32Slot(1, limit, 0)

def AddLimit(builder, limit):
    GetUserNotificationsRequestAddLimit(builder, limit)

def GetUserNotificationsRequestAddOffset(builder, offset):
    builder.PrependInt32Slot(2, offset, 0)

def AddOffset(builder, offset):
    GetUserNotificationsRequestAddOffset(builder, offset)

def GetUserNotificationsRequestAddStatusFilter(builder, statusFilter):
    builder.PrependInt32Slot(3, statusFilter, 0)

def AddStatusFilter(builder, statusFilter):
    GetUserNotificationsRequestAddStatusFilter(builder, statusFilter)

def GetUserNotificationsRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return GetUserNotificationsRequestEnd(builder)
