# DO NOT EDIT!
# python generated by Buffman 💪
# Versions:
# 		Buffman: 1.0.0
# 		Flatc: v25.2.10

# namespace: services

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetUserResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetUserResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetUserResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetUserResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetUserResponse
    def User(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from services.User import User
            obj = User()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GetUserResponse
    def Found(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GetUserResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    GetUserResponseStart(builder)

def GetUserResponseAddUser(builder, user):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(user), 0)

def AddUser(builder, user):
    GetUserResponseAddUser(builder, user)

def GetUserResponseAddFound(builder, found):
    builder.PrependBoolSlot(1, found, 0)

def AddFound(builder, found):
    GetUserResponseAddFound(builder, found)

def GetUserResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return GetUserResponseEnd(builder)
