# DO NOT EDIT!
# python generated by Buffman 💪
# Versions:
# 		Buffman: 1.0.0
# 		Flatc: v25.2.10

# namespace: services

class NotificationType(object):
    NOTIFICATION_TYPE_UNKNOWN = 0
    NOTIFICATION_TYPE_EMAIL = 1
    NOTIFICATION_TYPE_SMS = 2
    NOTIFICATION_TYPE_PUSH = 3
    NOTIFICATION_TYPE_IN_APP = 4
