# DO NOT EDIT!
# python generated by Buffman 💪
# Versions:
# 		Buffman: 1.0.0
# 		Flatc: v25.2.10

# namespace: services

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UpdateUserStatusRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UpdateUserStatusRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUpdateUserStatusRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UpdateUserStatusRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UpdateUserStatusRequest
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UpdateUserStatusRequest
    def NewStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UpdateUserStatusRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    UpdateUserStatusRequestStart(builder)

def UpdateUserStatusRequestAddUserId(builder, userId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(userId), 0)

def AddUserId(builder, userId):
    UpdateUserStatusRequestAddUserId(builder, userId)

def UpdateUserStatusRequestAddNewStatus(builder, newStatus):
    builder.PrependInt32Slot(1, newStatus, 0)

def AddNewStatus(builder, newStatus):
    UpdateUserStatusRequestAddNewStatus(builder, newStatus)

def UpdateUserStatusRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return UpdateUserStatusRequestEnd(builder)
