# DO NOT EDIT!
# python generated by Buffman 💪
# Versions:
# 		Buffman: 1.0.0
# 		Flatc: v25.2.10

# namespace: services

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UpdateUserStatusResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UpdateUserStatusResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUpdateUserStatusResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UpdateUserStatusResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UpdateUserStatusResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # UpdateUserStatusResponse
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UpdateUserStatusResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    UpdateUserStatusResponseStart(builder)

def UpdateUserStatusResponseAddSuccess(builder, success):
    builder.PrependBoolSlot(0, success, 0)

def AddSuccess(builder, success):
    UpdateUserStatusResponseAddSuccess(builder, success)

def UpdateUserStatusResponseAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    UpdateUserStatusResponseAddMessage(builder, message)

def UpdateUserStatusResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return UpdateUserStatusResponseEnd(builder)
