/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "services/analytics_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(services_UserActivity, services_UserActivity, AUTO)


PB_BIND(services_UserActivity_PropertiesEntry, services_UserActivity_PropertiesEntry, AUTO)


PB_BIND(services_NotificationMetrics, services_NotificationMetrics, AUTO)


PB_BIND(services_UserAnalyticsRequest, services_UserAnalyticsRequest, AUTO)


PB_BIND(services_UserAnalyticsResponse, services_UserAnalyticsResponse, 2)


PB_BIND(services_SystemMetricsRequest, services_SystemMetricsRequest, AUTO)


PB_BIND(services_SystemMetricsResponse, services_SystemMetricsResponse, AUTO)


PB_BIND(services_SystemMetricsResponse_ActivityCountsEntry, services_SystemMetricsResponse_ActivityCountsEntry, AUTO)


PB_BIND(services_TrackUserActivityResponse, services_TrackUserActivityResponse, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

