/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SERVICES_SERVICES_NOTIFICATION_SERVICE_PB_H_INCLUDED
#define PB_SERVICES_SERVICES_NOTIFICATION_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "common/timestamp.pb.h"
#include "common/status.pb.h"
#include "services/user_service.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _services_NotificationType {
    services_NotificationType_NOTIFICATION_TYPE_UNKNOWN = 0,
    services_NotificationType_NOTIFICATION_TYPE_EMAIL = 1,
    services_NotificationType_NOTIFICATION_TYPE_SMS = 2,
    services_NotificationType_NOTIFICATION_TYPE_PUSH = 3,
    services_NotificationType_NOTIFICATION_TYPE_IN_APP = 4
} services_NotificationType;

typedef enum _services_Priority {
    services_Priority_PRIORITY_LOW = 0,
    services_Priority_PRIORITY_MEDIUM = 1,
    services_Priority_PRIORITY_HIGH = 2,
    services_Priority_PRIORITY_URGENT = 3
} services_Priority;

/* Struct definitions */
typedef struct _services_Notification {
    pb_callback_t notification_id;
    pb_callback_t recipient_user_id;
    services_NotificationType type;
    pb_callback_t title;
    pb_callback_t content;
    services_Priority priority;
    common_Status status;
    bool has_created_at;
    common_Timestamp created_at;
    bool has_sent_at;
    common_Timestamp sent_at;
    pb_callback_t metadata;
} services_Notification;

typedef struct _services_Notification_MetadataEntry {
    pb_callback_t key;
    pb_callback_t value;
} services_Notification_MetadataEntry;

typedef struct _services_SendNotificationRequest {
    pb_callback_t recipient_user_id;
    services_NotificationType type;
    pb_callback_t title;
    pb_callback_t content;
    services_Priority priority;
    pb_callback_t metadata;
} services_SendNotificationRequest;

typedef struct _services_SendNotificationRequest_MetadataEntry {
    pb_callback_t key;
    pb_callback_t value;
} services_SendNotificationRequest_MetadataEntry;

typedef struct _services_SendNotificationResponse {
    pb_callback_t notification_id;
    bool success;
    pb_callback_t message;
} services_SendNotificationResponse;

typedef struct _services_GetUserNotificationsRequest {
    pb_callback_t user_id;
    int32_t limit;
    int32_t offset;
    common_Status status_filter;
} services_GetUserNotificationsRequest;

typedef struct _services_GetUserNotificationsResponse {
    pb_callback_t notifications;
    int32_t total_count;
    bool has_user_info;
    services_User user_info; /* Dependency on user_service.proto */
} services_GetUserNotificationsResponse;

typedef struct _services_MarkNotificationAsReadRequest {
    pb_callback_t notification_id;
    pb_callback_t user_id;
} services_MarkNotificationAsReadRequest;

typedef struct _services_MarkNotificationAsReadResponse {
    bool success;
    pb_callback_t message;
} services_MarkNotificationAsReadResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _services_NotificationType_MIN services_NotificationType_NOTIFICATION_TYPE_UNKNOWN
#define _services_NotificationType_MAX services_NotificationType_NOTIFICATION_TYPE_IN_APP
#define _services_NotificationType_ARRAYSIZE ((services_NotificationType)(services_NotificationType_NOTIFICATION_TYPE_IN_APP+1))

#define _services_Priority_MIN services_Priority_PRIORITY_LOW
#define _services_Priority_MAX services_Priority_PRIORITY_URGENT
#define _services_Priority_ARRAYSIZE ((services_Priority)(services_Priority_PRIORITY_URGENT+1))

#define services_Notification_type_ENUMTYPE services_NotificationType
#define services_Notification_priority_ENUMTYPE services_Priority
#define services_Notification_status_ENUMTYPE common_Status


#define services_SendNotificationRequest_type_ENUMTYPE services_NotificationType
#define services_SendNotificationRequest_priority_ENUMTYPE services_Priority



#define services_GetUserNotificationsRequest_status_filter_ENUMTYPE common_Status





/* Initializer values for message structs */
#define services_Notification_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, _services_NotificationType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, _services_Priority_MIN, _common_Status_MIN, false, common_Timestamp_init_default, false, common_Timestamp_init_default, {{NULL}, NULL}}
#define services_Notification_MetadataEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_SendNotificationRequest_init_default {{{NULL}, NULL}, _services_NotificationType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, _services_Priority_MIN, {{NULL}, NULL}}
#define services_SendNotificationRequest_MetadataEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_SendNotificationResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define services_GetUserNotificationsRequest_init_default {{{NULL}, NULL}, 0, 0, _common_Status_MIN}
#define services_GetUserNotificationsResponse_init_default {{{NULL}, NULL}, 0, false, services_User_init_default}
#define services_MarkNotificationAsReadRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_MarkNotificationAsReadResponse_init_default {0, {{NULL}, NULL}}
#define services_Notification_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, _services_NotificationType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, _services_Priority_MIN, _common_Status_MIN, false, common_Timestamp_init_zero, false, common_Timestamp_init_zero, {{NULL}, NULL}}
#define services_Notification_MetadataEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_SendNotificationRequest_init_zero {{{NULL}, NULL}, _services_NotificationType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, _services_Priority_MIN, {{NULL}, NULL}}
#define services_SendNotificationRequest_MetadataEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_SendNotificationResponse_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define services_GetUserNotificationsRequest_init_zero {{{NULL}, NULL}, 0, 0, _common_Status_MIN}
#define services_GetUserNotificationsResponse_init_zero {{{NULL}, NULL}, 0, false, services_User_init_zero}
#define services_MarkNotificationAsReadRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define services_MarkNotificationAsReadResponse_init_zero {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define services_Notification_notification_id_tag 1
#define services_Notification_recipient_user_id_tag 2
#define services_Notification_type_tag           3
#define services_Notification_title_tag          4
#define services_Notification_content_tag        5
#define services_Notification_priority_tag       6
#define services_Notification_status_tag         7
#define services_Notification_created_at_tag     8
#define services_Notification_sent_at_tag        9
#define services_Notification_metadata_tag       10
#define services_Notification_MetadataEntry_key_tag 1
#define services_Notification_MetadataEntry_value_tag 2
#define services_SendNotificationRequest_recipient_user_id_tag 1
#define services_SendNotificationRequest_type_tag 2
#define services_SendNotificationRequest_title_tag 3
#define services_SendNotificationRequest_content_tag 4
#define services_SendNotificationRequest_priority_tag 5
#define services_SendNotificationRequest_metadata_tag 6
#define services_SendNotificationRequest_MetadataEntry_key_tag 1
#define services_SendNotificationRequest_MetadataEntry_value_tag 2
#define services_SendNotificationResponse_notification_id_tag 1
#define services_SendNotificationResponse_success_tag 2
#define services_SendNotificationResponse_message_tag 3
#define services_GetUserNotificationsRequest_user_id_tag 1
#define services_GetUserNotificationsRequest_limit_tag 2
#define services_GetUserNotificationsRequest_offset_tag 3
#define services_GetUserNotificationsRequest_status_filter_tag 4
#define services_GetUserNotificationsResponse_notifications_tag 1
#define services_GetUserNotificationsResponse_total_count_tag 2
#define services_GetUserNotificationsResponse_user_info_tag 3
#define services_MarkNotificationAsReadRequest_notification_id_tag 1
#define services_MarkNotificationAsReadRequest_user_id_tag 2
#define services_MarkNotificationAsReadResponse_success_tag 1
#define services_MarkNotificationAsReadResponse_message_tag 2

/* Struct field encoding specification for nanopb */
#define services_Notification_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   notification_id,   1) \
X(a, CALLBACK, SINGULAR, STRING,   recipient_user_id,   2) \
X(a, STATIC,   SINGULAR, UENUM,    type,              3) \
X(a, CALLBACK, SINGULAR, STRING,   title,             4) \
X(a, CALLBACK, SINGULAR, STRING,   content,           5) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          6) \
X(a, STATIC,   SINGULAR, UENUM,    status,            7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  created_at,        8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sent_at,           9) \
X(a, CALLBACK, REPEATED, MESSAGE,  metadata,         10)
#define services_Notification_CALLBACK pb_default_field_callback
#define services_Notification_DEFAULT NULL
#define services_Notification_created_at_MSGTYPE common_Timestamp
#define services_Notification_sent_at_MSGTYPE common_Timestamp
#define services_Notification_metadata_MSGTYPE services_Notification_MetadataEntry

#define services_Notification_MetadataEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define services_Notification_MetadataEntry_CALLBACK pb_default_field_callback
#define services_Notification_MetadataEntry_DEFAULT NULL

#define services_SendNotificationRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   recipient_user_id,   1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, CALLBACK, SINGULAR, STRING,   title,             3) \
X(a, CALLBACK, SINGULAR, STRING,   content,           4) \
X(a, STATIC,   SINGULAR, UENUM,    priority,          5) \
X(a, CALLBACK, REPEATED, MESSAGE,  metadata,          6)
#define services_SendNotificationRequest_CALLBACK pb_default_field_callback
#define services_SendNotificationRequest_DEFAULT NULL
#define services_SendNotificationRequest_metadata_MSGTYPE services_SendNotificationRequest_MetadataEntry

#define services_SendNotificationRequest_MetadataEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define services_SendNotificationRequest_MetadataEntry_CALLBACK pb_default_field_callback
#define services_SendNotificationRequest_MetadataEntry_DEFAULT NULL

#define services_SendNotificationResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   notification_id,   1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, CALLBACK, SINGULAR, STRING,   message,           3)
#define services_SendNotificationResponse_CALLBACK pb_default_field_callback
#define services_SendNotificationResponse_DEFAULT NULL

#define services_GetUserNotificationsRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   user_id,           1) \
X(a, STATIC,   SINGULAR, INT32,    limit,             2) \
X(a, STATIC,   SINGULAR, INT32,    offset,            3) \
X(a, STATIC,   SINGULAR, UENUM,    status_filter,     4)
#define services_GetUserNotificationsRequest_CALLBACK pb_default_field_callback
#define services_GetUserNotificationsRequest_DEFAULT NULL

#define services_GetUserNotificationsResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  notifications,     1) \
X(a, STATIC,   SINGULAR, INT32,    total_count,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user_info,         3)
#define services_GetUserNotificationsResponse_CALLBACK pb_default_field_callback
#define services_GetUserNotificationsResponse_DEFAULT NULL
#define services_GetUserNotificationsResponse_notifications_MSGTYPE services_Notification
#define services_GetUserNotificationsResponse_user_info_MSGTYPE services_User

#define services_MarkNotificationAsReadRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   notification_id,   1) \
X(a, CALLBACK, SINGULAR, STRING,   user_id,           2)
#define services_MarkNotificationAsReadRequest_CALLBACK pb_default_field_callback
#define services_MarkNotificationAsReadRequest_DEFAULT NULL

#define services_MarkNotificationAsReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define services_MarkNotificationAsReadResponse_CALLBACK pb_default_field_callback
#define services_MarkNotificationAsReadResponse_DEFAULT NULL

extern const pb_msgdesc_t services_Notification_msg;
extern const pb_msgdesc_t services_Notification_MetadataEntry_msg;
extern const pb_msgdesc_t services_SendNotificationRequest_msg;
extern const pb_msgdesc_t services_SendNotificationRequest_MetadataEntry_msg;
extern const pb_msgdesc_t services_SendNotificationResponse_msg;
extern const pb_msgdesc_t services_GetUserNotificationsRequest_msg;
extern const pb_msgdesc_t services_GetUserNotificationsResponse_msg;
extern const pb_msgdesc_t services_MarkNotificationAsReadRequest_msg;
extern const pb_msgdesc_t services_MarkNotificationAsReadResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define services_Notification_fields &services_Notification_msg
#define services_Notification_MetadataEntry_fields &services_Notification_MetadataEntry_msg
#define services_SendNotificationRequest_fields &services_SendNotificationRequest_msg
#define services_SendNotificationRequest_MetadataEntry_fields &services_SendNotificationRequest_MetadataEntry_msg
#define services_SendNotificationResponse_fields &services_SendNotificationResponse_msg
#define services_GetUserNotificationsRequest_fields &services_GetUserNotificationsRequest_msg
#define services_GetUserNotificationsResponse_fields &services_GetUserNotificationsResponse_msg
#define services_MarkNotificationAsReadRequest_fields &services_MarkNotificationAsReadRequest_msg
#define services_MarkNotificationAsReadResponse_fields &services_MarkNotificationAsReadResponse_msg

/* Maximum encoded size of messages (where known) */
/* services_Notification_size depends on runtime parameters */
/* services_Notification_MetadataEntry_size depends on runtime parameters */
/* services_SendNotificationRequest_size depends on runtime parameters */
/* services_SendNotificationRequest_MetadataEntry_size depends on runtime parameters */
/* services_SendNotificationResponse_size depends on runtime parameters */
/* services_GetUserNotificationsRequest_size depends on runtime parameters */
/* services_GetUserNotificationsResponse_size depends on runtime parameters */
/* services_MarkNotificationAsReadRequest_size depends on runtime parameters */
/* services_MarkNotificationAsReadResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
