/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "services/notification_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(services_Notification, services_Notification, AUTO)


PB_BIND(services_Notification_MetadataEntry, services_Notification_MetadataEntry, AUTO)


PB_BIND(services_SendNotificationRequest, services_SendNotificationRequest, AUTO)


PB_BIND(services_SendNotificationRequest_MetadataEntry, services_SendNotificationRequest_MetadataEntry, AUTO)


PB_BIND(services_SendNotificationResponse, services_SendNotificationResponse, AUTO)


PB_BIND(services_GetUserNotificationsRequest, services_GetUserNotificationsRequest, AUTO)


PB_BIND(services_GetUserNotificationsResponse, services_GetUserNotificationsResponse, AUTO)


PB_BIND(services_MarkNotificationAsReadRequest, services_MarkNotificationAsReadRequest, AUTO)


PB_BIND(services_MarkNotificationAsReadResponse, services_MarkNotificationAsReadResponse, AUTO)







