// DO NOT EDIT!
// php generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
// automatically generated by the FlatBuffers compiler, do not modify

namespace common;

class Status
{
    const STATUS_UNKNOWN = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;
    const STATUS_PENDING = 3;
    const STATUS_SUSPENDED = 4;

    private static $names = array(
        Status::STATUS_UNKNOWN=>"STATUS_UNKNOWN",
        Status::STATUS_ACTIVE=>"STATUS_ACTIVE",
        Status::STATUS_INACTIVE=>"STATUS_INACTIVE",
        Status::STATUS_PENDING=>"STATUS_PENDING",
        Status::STATUS_SUSPENDED=>"STATUS_SUSPENDED",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
