// DO NOT EDIT!
// ts generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Address } from '../common/address.js';


export class CreateUserRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreateUserRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreateUserRequest(bb:flatbuffers.ByteBuffer, obj?:CreateUserRequest):CreateUserRequest {
  return (obj || new CreateUserRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreateUserRequest(bb:flatbuffers.ByteBuffer, obj?:CreateUserRequest):CreateUserRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreateUserRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

email():string|null
email(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
email(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

firstName():string|null
firstName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
firstName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastName():string|null
lastName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

address(obj?:Address):Address|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Address()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

roles(index: number):string
roles(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
roles(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

rolesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCreateUserRequest(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addEmail(builder:flatbuffers.Builder, emailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, emailOffset, 0);
}

static addFirstName(builder:flatbuffers.Builder, firstNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, firstNameOffset, 0);
}

static addLastName(builder:flatbuffers.Builder, lastNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, lastNameOffset, 0);
}

static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, addressOffset, 0);
}

static addRoles(builder:flatbuffers.Builder, rolesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, rolesOffset, 0);
}

static createRolesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRolesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCreateUserRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
