// DO NOT EDIT!
// ts generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SendNotificationResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SendNotificationResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSendNotificationResponse(bb:flatbuffers.ByteBuffer, obj?:SendNotificationResponse):SendNotificationResponse {
  return (obj || new SendNotificationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSendNotificationResponse(bb:flatbuffers.ByteBuffer, obj?:SendNotificationResponse):SendNotificationResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SendNotificationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

notificationId():string|null
notificationId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
notificationId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

success():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSendNotificationResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addNotificationId(builder:flatbuffers.Builder, notificationIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, notificationIdOffset, 0);
}

static addSuccess(builder:flatbuffers.Builder, success:boolean) {
  builder.addFieldInt8(1, +success, +false);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, messageOffset, 0);
}

static endSendNotificationResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSendNotificationResponse(builder:flatbuffers.Builder, notificationIdOffset:flatbuffers.Offset, success:boolean, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  SendNotificationResponse.startSendNotificationResponse(builder);
  SendNotificationResponse.addNotificationId(builder, notificationIdOffset);
  SendNotificationResponse.addSuccess(builder, success);
  SendNotificationResponse.addMessage(builder, messageOffset);
  return SendNotificationResponse.endSendNotificationResponse(builder);
}
}
