// DO NOT EDIT!
// ts generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Timestamp } from '../common/timestamp.js';


export class SystemMetricsRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SystemMetricsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSystemMetricsRequest(bb:flatbuffers.ByteBuffer, obj?:SystemMetricsRequest):SystemMetricsRequest {
  return (obj || new SystemMetricsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSystemMetricsRequest(bb:flatbuffers.ByteBuffer, obj?:SystemMetricsRequest):SystemMetricsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SystemMetricsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

startDate(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Timestamp()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

endDate(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Timestamp()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSystemMetricsRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addStartDate(builder:flatbuffers.Builder, startDateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, startDateOffset, 0);
}

static addEndDate(builder:flatbuffers.Builder, endDateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, endDateOffset, 0);
}

static endSystemMetricsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
