// DO NOT EDIT!
// ts generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Timestamp } from '../common/timestamp.js';


export class UserAnalyticsRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserAnalyticsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserAnalyticsRequest(bb:flatbuffers.ByteBuffer, obj?:UserAnalyticsRequest):UserAnalyticsRequest {
  return (obj || new UserAnalyticsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserAnalyticsRequest(bb:flatbuffers.ByteBuffer, obj?:UserAnalyticsRequest):UserAnalyticsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserAnalyticsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():string|null
userId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

startDate(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Timestamp()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

endDate(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Timestamp()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startUserAnalyticsRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUserId(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userIdOffset, 0);
}

static addStartDate(builder:flatbuffers.Builder, startDateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, startDateOffset, 0);
}

static addEndDate(builder:flatbuffers.Builder, endDateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, endDateOffset, 0);
}

static endUserAnalyticsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
