/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COMMON_COMMON_ADDRESS_PB_H_INCLUDED
#define PB_COMMON_COMMON_ADDRESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _common_Address {
    pb_callback_t street;
    pb_callback_t city;
    pb_callback_t state;
    pb_callback_t postal_code;
    pb_callback_t country;
} common_Address;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define common_Address_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define common_Address_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define common_Address_street_tag                1
#define common_Address_city_tag                  2
#define common_Address_state_tag                 3
#define common_Address_postal_code_tag           4
#define common_Address_country_tag               5

/* Struct field encoding specification for nanopb */
#define common_Address_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   street,            1) \
X(a, CALLBACK, SINGULAR, STRING,   city,              2) \
X(a, CALLBACK, SINGULAR, STRING,   state,             3) \
X(a, CALLBACK, SINGULAR, STRING,   postal_code,       4) \
X(a, CALLBACK, SINGULAR, STRING,   country,           5)
#define common_Address_CALLBACK pb_default_field_callback
#define common_Address_DEFAULT NULL

extern const pb_msgdesc_t common_Address_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define common_Address_fields &common_Address_msg

/* Maximum encoded size of messages (where known) */
/* common_Address_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
