// DO NOT EDIT!
// php generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
// automatically generated by the FlatBuffers compiler, do not modify

namespace services;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class GetUserNotificationsRequest extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return GetUserNotificationsRequest
     */
    public static function getRootAsGetUserNotificationsRequest(ByteBuffer $bb)
    {
        $obj = new GetUserNotificationsRequest();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return GetUserNotificationsRequest
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getUserId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return int
     */
    public function getLimit()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getOffset()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : 0;
    }

    /**
     * @return int
     */
    public function getStatusFilter()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->bb->getInt($o + $this->bb_pos) : \common\Status::STATUS_UNKNOWN;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startGetUserNotificationsRequest(FlatBufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return GetUserNotificationsRequest
     */
    public static function createGetUserNotificationsRequest(FlatBufferBuilder $builder, $user_id, $limit, $offset, $status_filter)
    {
        $builder->startObject(4);
        self::addUserId($builder, $user_id);
        self::addLimit($builder, $limit);
        self::addOffset($builder, $offset);
        self::addStatusFilter($builder, $status_filter);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addUserId(FlatBufferBuilder $builder, $userId)
    {
        $builder->addOffsetX(0, $userId, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addLimit(FlatBufferBuilder $builder, $limit)
    {
        $builder->addIntX(1, $limit, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addOffset(FlatBufferBuilder $builder, $offset)
    {
        $builder->addIntX(2, $offset, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param int
     * @return void
     */
    public static function addStatusFilter(FlatBufferBuilder $builder, $statusFilter)
    {
        $builder->addIntX(3, $statusFilter, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endGetUserNotificationsRequest(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
