// DO NOT EDIT!
// php generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
// automatically generated by the FlatBuffers compiler, do not modify

namespace services;

class NotificationType
{
    const NOTIFICATION_TYPE_UNKNOWN = 0;
    const NOTIFICATION_TYPE_EMAIL = 1;
    const NOTIFICATION_TYPE_SMS = 2;
    const NOTIFICATION_TYPE_PUSH = 3;
    const NOTIFICATION_TYPE_IN_APP = 4;

    private static $names = array(
        NotificationType::NOTIFICATION_TYPE_UNKNOWN=>"NOTIFICATION_TYPE_UNKNOWN",
        NotificationType::NOTIFICATION_TYPE_EMAIL=>"NOTIFICATION_TYPE_EMAIL",
        NotificationType::NOTIFICATION_TYPE_SMS=>"NOTIFICATION_TYPE_SMS",
        NotificationType::NOTIFICATION_TYPE_PUSH=>"NOTIFICATION_TYPE_PUSH",
        NotificationType::NOTIFICATION_TYPE_IN_APP=>"NOTIFICATION_TYPE_IN_APP",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
