// DO NOT EDIT!
// php generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
// automatically generated by the FlatBuffers compiler, do not modify

namespace services;

class Priority
{
    const PRIORITY_LOW = 0;
    const PRIORITY_MEDIUM = 1;
    const PRIORITY_HIGH = 2;
    const PRIORITY_URGENT = 3;

    private static $names = array(
        Priority::PRIORITY_LOW=>"PRIORITY_LOW",
        Priority::PRIORITY_MEDIUM=>"PRIORITY_MEDIUM",
        Priority::PRIORITY_HIGH=>"PRIORITY_HIGH",
        Priority::PRIORITY_URGENT=>"PRIORITY_URGENT",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
