// DO NOT EDIT!
// swift generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum common_Status: Int32, Enum, Verifiable {
  public typealias T = Int32
  public static var byteSize: Int { return MemoryLayout<Int32>.size }
  public var value: Int32 { return self.rawValue }
  case statusUnknown = 0
  case statusActive = 1
  case statusInactive = 2
  case statusPending = 3
  case statusSuspended = 4

  public static var max: common_Status { return .statusSuspended }
  public static var min: common_Status { return .statusUnknown }
}


