// DO NOT EDIT!
// go generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package services

import "strconv"

type Priority int32

const (
	PriorityPRIORITY_LOW    Priority = 0
	PriorityPRIORITY_MEDIUM Priority = 1
	PriorityPRIORITY_HIGH   Priority = 2
	PriorityPRIORITY_URGENT Priority = 3
)

var EnumNamesPriority = map[Priority]string{
	PriorityPRIORITY_LOW:    "PRIORITY_LOW",
	PriorityPRIORITY_MEDIUM: "PRIORITY_MEDIUM",
	PriorityPRIORITY_HIGH:   "PRIORITY_HIGH",
	PriorityPRIORITY_URGENT: "PRIORITY_URGENT",
}

var EnumValuesPriority = map[string]Priority{
	"PRIORITY_LOW":    PriorityPRIORITY_LOW,
	"PRIORITY_MEDIUM": PriorityPRIORITY_MEDIUM,
	"PRIORITY_HIGH":   PriorityPRIORITY_HIGH,
	"PRIORITY_URGENT": PriorityPRIORITY_URGENT,
}

func (v Priority) String() string {
	if s, ok := EnumNamesPriority[v]; ok {
		return s
	}
	return "Priority(" + strconv.FormatInt(int64(v), 10) + ")"
}
