// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CreateUserRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CreateUserRequest getRootAsCreateUserRequest(ByteBuffer _bb) { return getRootAsCreateUserRequest(_bb, new CreateUserRequest()); }
  public static CreateUserRequest getRootAsCreateUserRequest(ByteBuffer _bb, CreateUserRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CreateUserRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String email() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer emailAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer emailInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String firstName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer firstNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer firstNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String lastName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lastNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer lastNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public com.fb.common.Address address() { return address(new com.fb.common.Address()); }
  public com.fb.common.Address address(com.fb.common.Address obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String roles(int j) { int o = __offset(12); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int rolesLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public StringVector rolesVector() { return rolesVector(new StringVector()); }
  public StringVector rolesVector(StringVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createCreateUserRequest(FlatBufferBuilder builder,
      int emailOffset,
      int firstNameOffset,
      int lastNameOffset,
      int addressOffset,
      int rolesOffset) {
    builder.startTable(5);
    CreateUserRequest.addRoles(builder, rolesOffset);
    CreateUserRequest.addAddress(builder, addressOffset);
    CreateUserRequest.addLastName(builder, lastNameOffset);
    CreateUserRequest.addFirstName(builder, firstNameOffset);
    CreateUserRequest.addEmail(builder, emailOffset);
    return CreateUserRequest.endCreateUserRequest(builder);
  }

  public static void startCreateUserRequest(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addEmail(FlatBufferBuilder builder, int emailOffset) { builder.addOffset(0, emailOffset, 0); }
  public static void addFirstName(FlatBufferBuilder builder, int firstNameOffset) { builder.addOffset(1, firstNameOffset, 0); }
  public static void addLastName(FlatBufferBuilder builder, int lastNameOffset) { builder.addOffset(2, lastNameOffset, 0); }
  public static void addAddress(FlatBufferBuilder builder, int addressOffset) { builder.addOffset(3, addressOffset, 0); }
  public static void addRoles(FlatBufferBuilder builder, int rolesOffset) { builder.addOffset(4, rolesOffset, 0); }
  public static int createRolesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRolesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCreateUserRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CreateUserRequest get(int j) { return get(new CreateUserRequest(), j); }
    public CreateUserRequest get(CreateUserRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

