// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CreateUserResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static CreateUserResponse getRootAsCreateUserResponse(ByteBuffer _bb) { return getRootAsCreateUserResponse(_bb, new CreateUserResponse()); }
  public static CreateUserResponse getRootAsCreateUserResponse(ByteBuffer _bb, CreateUserResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CreateUserResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.fb.services.User user() { return user(new com.fb.services.User()); }
  public com.fb.services.User user(com.fb.services.User obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public boolean success() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createCreateUserResponse(FlatBufferBuilder builder,
      int userOffset,
      boolean success,
      int messageOffset) {
    builder.startTable(3);
    CreateUserResponse.addMessage(builder, messageOffset);
    CreateUserResponse.addUser(builder, userOffset);
    CreateUserResponse.addSuccess(builder, success);
    return CreateUserResponse.endCreateUserResponse(builder);
  }

  public static void startCreateUserResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUser(FlatBufferBuilder builder, int userOffset) { builder.addOffset(0, userOffset, 0); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(1, success, false); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endCreateUserResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CreateUserResponse get(int j) { return get(new CreateUserResponse(), j); }
    public CreateUserResponse get(CreateUserResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

