// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetUserNotificationsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static GetUserNotificationsRequest getRootAsGetUserNotificationsRequest(ByteBuffer _bb) { return getRootAsGetUserNotificationsRequest(_bb, new GetUserNotificationsRequest()); }
  public static GetUserNotificationsRequest getRootAsGetUserNotificationsRequest(ByteBuffer _bb, GetUserNotificationsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetUserNotificationsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer userIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int limit() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int offset() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int statusFilter() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createGetUserNotificationsRequest(FlatBufferBuilder builder,
      int userIdOffset,
      int limit,
      int offset,
      int statusFilter) {
    builder.startTable(4);
    GetUserNotificationsRequest.addStatusFilter(builder, statusFilter);
    GetUserNotificationsRequest.addOffset(builder, offset);
    GetUserNotificationsRequest.addLimit(builder, limit);
    GetUserNotificationsRequest.addUserId(builder, userIdOffset);
    return GetUserNotificationsRequest.endGetUserNotificationsRequest(builder);
  }

  public static void startGetUserNotificationsRequest(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static void addLimit(FlatBufferBuilder builder, int limit) { builder.addInt(1, limit, 0); }
  public static void addOffset(FlatBufferBuilder builder, int offset) { builder.addInt(2, offset, 0); }
  public static void addStatusFilter(FlatBufferBuilder builder, int statusFilter) { builder.addInt(3, statusFilter, 0); }
  public static int endGetUserNotificationsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetUserNotificationsRequest get(int j) { return get(new GetUserNotificationsRequest(), j); }
    public GetUserNotificationsRequest get(GetUserNotificationsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

