// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

@SuppressWarnings("unused")
public final class NotificationType {
  private NotificationType() { }
  public static final int NOTIFICATION_TYPE_UNKNOWN = 0;
  public static final int NOTIFICATION_TYPE_EMAIL = 1;
  public static final int NOTIFICATION_TYPE_SMS = 2;
  public static final int NOTIFICATION_TYPE_PUSH = 3;
  public static final int NOTIFICATION_TYPE_IN_APP = 4;

  public static final String[] names = { "NOTIFICATION_TYPE_UNKNOWN", "NOTIFICATION_TYPE_EMAIL", "NOTIFICATION_TYPE_SMS", "NOTIFICATION_TYPE_PUSH", "NOTIFICATION_TYPE_IN_APP", };

  public static String name(int e) { return names[e]; }
}

