// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class NotificationMetrics extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static NotificationMetrics getRootAsNotificationMetrics(ByteBuffer _bb) { return getRootAsNotificationMetrics(_bb, new NotificationMetrics()); }
  public static NotificationMetrics getRootAsNotificationMetrics(ByteBuffer _bb, NotificationMetrics obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public NotificationMetrics __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String notificationId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer notificationIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer notificationIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int type() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean delivered() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean opened() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean clicked() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public com.fb.common.Timestamp deliveredAt() { return deliveredAt(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp deliveredAt(com.fb.common.Timestamp obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.fb.common.Timestamp openedAt() { return openedAt(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp openedAt(com.fb.common.Timestamp obj) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.fb.common.Timestamp clickedAt() { return clickedAt(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp clickedAt(com.fb.common.Timestamp obj) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createNotificationMetrics(FlatBufferBuilder builder,
      int notificationIdOffset,
      int type,
      boolean delivered,
      boolean opened,
      boolean clicked,
      int deliveredAtOffset,
      int openedAtOffset,
      int clickedAtOffset) {
    builder.startTable(8);
    NotificationMetrics.addClickedAt(builder, clickedAtOffset);
    NotificationMetrics.addOpenedAt(builder, openedAtOffset);
    NotificationMetrics.addDeliveredAt(builder, deliveredAtOffset);
    NotificationMetrics.addType(builder, type);
    NotificationMetrics.addNotificationId(builder, notificationIdOffset);
    NotificationMetrics.addClicked(builder, clicked);
    NotificationMetrics.addOpened(builder, opened);
    NotificationMetrics.addDelivered(builder, delivered);
    return NotificationMetrics.endNotificationMetrics(builder);
  }

  public static void startNotificationMetrics(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addNotificationId(FlatBufferBuilder builder, int notificationIdOffset) { builder.addOffset(0, notificationIdOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(1, type, 0); }
  public static void addDelivered(FlatBufferBuilder builder, boolean delivered) { builder.addBoolean(2, delivered, false); }
  public static void addOpened(FlatBufferBuilder builder, boolean opened) { builder.addBoolean(3, opened, false); }
  public static void addClicked(FlatBufferBuilder builder, boolean clicked) { builder.addBoolean(4, clicked, false); }
  public static void addDeliveredAt(FlatBufferBuilder builder, int deliveredAtOffset) { builder.addOffset(5, deliveredAtOffset, 0); }
  public static void addOpenedAt(FlatBufferBuilder builder, int openedAtOffset) { builder.addOffset(6, openedAtOffset, 0); }
  public static void addClickedAt(FlatBufferBuilder builder, int clickedAtOffset) { builder.addOffset(7, clickedAtOffset, 0); }
  public static int endNotificationMetrics(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public NotificationMetrics get(int j) { return get(new NotificationMetrics(), j); }
    public NotificationMetrics get(NotificationMetrics obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

