// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SendNotificationRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SendNotificationRequest getRootAsSendNotificationRequest(ByteBuffer _bb) { return getRootAsSendNotificationRequest(_bb, new SendNotificationRequest()); }
  public static SendNotificationRequest getRootAsSendNotificationRequest(ByteBuffer _bb, SendNotificationRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SendNotificationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String recipientUserId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer recipientUserIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer recipientUserIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int type() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String title() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer titleAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer titleInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String content() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int priority() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public com.fb.services.SendNotificationRequest_.MetadataEntry metadata(int j) { return metadata(new com.fb.services.SendNotificationRequest_.MetadataEntry(), j); }
  public com.fb.services.SendNotificationRequest_.MetadataEntry metadata(com.fb.services.SendNotificationRequest_.MetadataEntry obj, int j) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int metadataLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public com.fb.services.SendNotificationRequest_.MetadataEntry.Vector metadataVector() { return metadataVector(new com.fb.services.SendNotificationRequest_.MetadataEntry.Vector()); }
  public com.fb.services.SendNotificationRequest_.MetadataEntry.Vector metadataVector(com.fb.services.SendNotificationRequest_.MetadataEntry.Vector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createSendNotificationRequest(FlatBufferBuilder builder,
      int recipientUserIdOffset,
      int type,
      int titleOffset,
      int contentOffset,
      int priority,
      int metadataOffset) {
    builder.startTable(6);
    SendNotificationRequest.addMetadata(builder, metadataOffset);
    SendNotificationRequest.addPriority(builder, priority);
    SendNotificationRequest.addContent(builder, contentOffset);
    SendNotificationRequest.addTitle(builder, titleOffset);
    SendNotificationRequest.addType(builder, type);
    SendNotificationRequest.addRecipientUserId(builder, recipientUserIdOffset);
    return SendNotificationRequest.endSendNotificationRequest(builder);
  }

  public static void startSendNotificationRequest(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addRecipientUserId(FlatBufferBuilder builder, int recipientUserIdOffset) { builder.addOffset(0, recipientUserIdOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(1, type, 0); }
  public static void addTitle(FlatBufferBuilder builder, int titleOffset) { builder.addOffset(2, titleOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(3, contentOffset, 0); }
  public static void addPriority(FlatBufferBuilder builder, int priority) { builder.addInt(4, priority, 0); }
  public static void addMetadata(FlatBufferBuilder builder, int metadataOffset) { builder.addOffset(5, metadataOffset, 0); }
  public static int createMetadataVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMetadataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSendNotificationRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SendNotificationRequest get(int j) { return get(new SendNotificationRequest(), j); }
    public SendNotificationRequest get(SendNotificationRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

