// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SystemMetricsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SystemMetricsRequest getRootAsSystemMetricsRequest(ByteBuffer _bb) { return getRootAsSystemMetricsRequest(_bb, new SystemMetricsRequest()); }
  public static SystemMetricsRequest getRootAsSystemMetricsRequest(ByteBuffer _bb, SystemMetricsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SystemMetricsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.fb.common.Timestamp startDate() { return startDate(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp startDate(com.fb.common.Timestamp obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.fb.common.Timestamp endDate() { return endDate(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp endDate(com.fb.common.Timestamp obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createSystemMetricsRequest(FlatBufferBuilder builder,
      int startDateOffset,
      int endDateOffset) {
    builder.startTable(2);
    SystemMetricsRequest.addEndDate(builder, endDateOffset);
    SystemMetricsRequest.addStartDate(builder, startDateOffset);
    return SystemMetricsRequest.endSystemMetricsRequest(builder);
  }

  public static void startSystemMetricsRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStartDate(FlatBufferBuilder builder, int startDateOffset) { builder.addOffset(0, startDateOffset, 0); }
  public static void addEndDate(FlatBufferBuilder builder, int endDateOffset) { builder.addOffset(1, endDateOffset, 0); }
  public static int endSystemMetricsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SystemMetricsRequest get(int j) { return get(new SystemMetricsRequest(), j); }
    public SystemMetricsRequest get(SystemMetricsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

