// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class UserAnalyticsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static UserAnalyticsRequest getRootAsUserAnalyticsRequest(ByteBuffer _bb) { return getRootAsUserAnalyticsRequest(_bb, new UserAnalyticsRequest()); }
  public static UserAnalyticsRequest getRootAsUserAnalyticsRequest(ByteBuffer _bb, UserAnalyticsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UserAnalyticsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer userIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public com.fb.common.Timestamp startDate() { return startDate(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp startDate(com.fb.common.Timestamp obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.fb.common.Timestamp endDate() { return endDate(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp endDate(com.fb.common.Timestamp obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createUserAnalyticsRequest(FlatBufferBuilder builder,
      int userIdOffset,
      int startDateOffset,
      int endDateOffset) {
    builder.startTable(3);
    UserAnalyticsRequest.addEndDate(builder, endDateOffset);
    UserAnalyticsRequest.addStartDate(builder, startDateOffset);
    UserAnalyticsRequest.addUserId(builder, userIdOffset);
    return UserAnalyticsRequest.endUserAnalyticsRequest(builder);
  }

  public static void startUserAnalyticsRequest(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static void addStartDate(FlatBufferBuilder builder, int startDateOffset) { builder.addOffset(1, startDateOffset, 0); }
  public static void addEndDate(FlatBufferBuilder builder, int endDateOffset) { builder.addOffset(2, endDateOffset, 0); }
  public static int endUserAnalyticsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UserAnalyticsRequest get(int j) { return get(new UserAnalyticsRequest(), j); }
    public UserAnalyticsRequest get(UserAnalyticsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

