// DO NOT EDIT!
// java generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package com.fb.services;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class User extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static User getRootAsUser(ByteBuffer _bb) { return getRootAsUser(_bb, new User()); }
  public static User getRootAsUser(ByteBuffer _bb, User obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer userIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String email() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer emailAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer emailInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String firstName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer firstNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer firstNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String lastName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lastNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer lastNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public com.fb.common.Address address() { return address(new com.fb.common.Address()); }
  public com.fb.common.Address address(com.fb.common.Address obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int status() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public com.fb.common.Timestamp createdAt() { return createdAt(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp createdAt(com.fb.common.Timestamp obj) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public com.fb.common.Timestamp updatedAt() { return updatedAt(new com.fb.common.Timestamp()); }
  public com.fb.common.Timestamp updatedAt(com.fb.common.Timestamp obj) { int o = __offset(18); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String roles(int j) { int o = __offset(20); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int rolesLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public StringVector rolesVector() { return rolesVector(new StringVector()); }
  public StringVector rolesVector(StringVector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createUser(FlatBufferBuilder builder,
      int userIdOffset,
      int emailOffset,
      int firstNameOffset,
      int lastNameOffset,
      int addressOffset,
      int status,
      int createdAtOffset,
      int updatedAtOffset,
      int rolesOffset) {
    builder.startTable(9);
    User.addRoles(builder, rolesOffset);
    User.addUpdatedAt(builder, updatedAtOffset);
    User.addCreatedAt(builder, createdAtOffset);
    User.addStatus(builder, status);
    User.addAddress(builder, addressOffset);
    User.addLastName(builder, lastNameOffset);
    User.addFirstName(builder, firstNameOffset);
    User.addEmail(builder, emailOffset);
    User.addUserId(builder, userIdOffset);
    return User.endUser(builder);
  }

  public static void startUser(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static void addEmail(FlatBufferBuilder builder, int emailOffset) { builder.addOffset(1, emailOffset, 0); }
  public static void addFirstName(FlatBufferBuilder builder, int firstNameOffset) { builder.addOffset(2, firstNameOffset, 0); }
  public static void addLastName(FlatBufferBuilder builder, int lastNameOffset) { builder.addOffset(3, lastNameOffset, 0); }
  public static void addAddress(FlatBufferBuilder builder, int addressOffset) { builder.addOffset(4, addressOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addInt(5, status, 0); }
  public static void addCreatedAt(FlatBufferBuilder builder, int createdAtOffset) { builder.addOffset(6, createdAtOffset, 0); }
  public static void addUpdatedAt(FlatBufferBuilder builder, int updatedAtOffset) { builder.addOffset(7, updatedAtOffset, 0); }
  public static void addRoles(FlatBufferBuilder builder, int rolesOffset) { builder.addOffset(8, rolesOffset, 0); }
  public static int createRolesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRolesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endUser(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public User get(int j) { return get(new User(), j); }
    public User get(User obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

