// DO NOT EDIT!
// go generated by Buffman 💪
// Versions:
// 		Buffman: 1.0.0
// 		Flatc: v25.2.10

package common

import "strconv"

type Status int32

const (
	StatusSTATUS_UNKNOWN   Status = 0
	StatusSTATUS_ACTIVE    Status = 1
	StatusSTATUS_INACTIVE  Status = 2
	StatusSTATUS_PENDING   Status = 3
	StatusSTATUS_SUSPENDED Status = 4
)

var EnumNamesStatus = map[Status]string{
	StatusSTATUS_UNKNOWN:   "STATUS_UNKNOWN",
	StatusSTATUS_ACTIVE:    "STATUS_ACTIVE",
	StatusSTATUS_INACTIVE:  "STATUS_INACTIVE",
	StatusSTATUS_PENDING:   "STATUS_PENDING",
	StatusSTATUS_SUSPENDED: "STATUS_SUSPENDED",
}

var EnumValuesStatus = map[string]Status{
	"STATUS_UNKNOWN":   StatusSTATUS_UNKNOWN,
	"STATUS_ACTIVE":    StatusSTATUS_ACTIVE,
	"STATUS_INACTIVE":  StatusSTATUS_INACTIVE,
	"STATUS_PENDING":   StatusSTATUS_PENDING,
	"STATUS_SUSPENDED": StatusSTATUS_SUSPENDED,
}

func (v Status) String() string {
	if s, ok := EnumNamesStatus[v]; ok {
		return s
	}
	return "Status(" + strconv.FormatInt(int64(v), 10) + ")"
}
