package template

import (
	"fmt"
	"strings"

	"github.com/the-protobuf-project/buffman/internal"
	"github.com/the-protobuf-project/buffman/internal/install"
)

// Template holds version information used when building file headers.
type Template struct {
	languagePrefix string
	FlatC          string
	Buffman        string
}

// NewTemplate creates a new Template for the given comment prefix (e.g. "//", "#", "--").
func NewTemplate(languagePrefix string) (*Template, error) {
	installer := install.NewManager()
	installer.RegisterInstaller(install.FlatbuffersInstaller, install.NewInstaller(install.FlatbuffersInstaller))
	flatc := installer.GetInstaller(install.FlatbuffersInstaller)
	version, err := flatc.GetVersion()
	if err != nil {
		return nil, err
	}
	return &Template{
		languagePrefix: languagePrefix,
		FlatC:          version,
		Buffman:        internal.Version,
	}, nil
}

// BuildHeader returns the standard "Code generated by buffman" header block.
// source is the input file that produced this output (e.g. "common/address.proto");
// pass "" to omit the source line.
func (t *Template) BuildHeader(source string) string {
	p := t.languagePrefix
	var b strings.Builder

	b.WriteString(p + " Code generated by buffman. DO NOT EDIT.\n")
	b.WriteString(p + " versions:\n")
	fmt.Fprintf(&b, p+" \tbuffman  v%s\n", t.Buffman)
	fmt.Fprintf(&b, p+" \tflatc    v%s\n", t.FlatC)
	if source != "" {
		b.WriteString(p + " source: " + source + "\n")
	}
	b.WriteString(p + "\n")
	b.WriteString(p + " buffman — https://github.com/the-protobuf-project/buffman\n")

	return b.String()
}
